### ISSUE TITLE
attempt to call field 'unpack' (a nil value)

### ISSUE THREAD

**Issue by hendursaga** [gbaptista/fnx#1]
```
$ fennel --version
Fennel 1.0.0 on Lua 5.1

$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

[clone repo and install dependencies]

$ fennel install.fnl

runtime error: attempt to call field 'unpack' (a nil value)
stack traceback:
  ./fnx/adapters/shell.fnl:8: in function 'smk->string'
  ./fnx/ports/out/shell.fnl:10: in function 'dispatch!'
  ./fnx/controllers/installer.fnl:21: in function ?
  (tail call)
  (tail call)
  (tail call)
  (tail call)
  (tail call)
  [C]: in function 'xpcall'
  fennel:5396: in function ?
  (tail call)
  [C]: in ?
```

It appears that fnx doesn't support Lua 5.1.5. I installed Lua 5.4.4 and the above error goes away. It might be good to mention the oldest supported Lua version.

**Comment by gbaptista** [comment]
I remember facing this issue with Lua in [another project](https://github.com/gbaptista/supernova/blob/0ebeb80ca36bd9bfb9a81b6ba9673af66145509d/supernova/helpers/table.lua).

I just added [backward compatibility](https://github.com/gbaptista/fnx/pull/3) to prevent this kind of error.

Thanks for reporting!
